# Generated by Django 5.1.15 on 2026-06-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_seed_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='shopstate',
            options={'ordering': ['week_start', 'key'], 'verbose_name': 'Shop state'},
        ),
        migrations.AddField(
            model_name='shopstate',
            name='week_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shopstate',
            name='key',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='shopstate',
            unique_together={('week_start', 'key')},
        ),
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='planner.person')),
            ],
            options={
                'ordering': ['week_start', 'id'],
                'unique_together': {('person', 'week_start')},
            },
        ),
        migrations.AddField(
            model_name='planassignment',
            name='week_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='planner.weekplan'),
        ),
    ]
